/**
 * JWT Configuration
 *
 * For production, use a strong secret key stored in environment variables.
 * The secret should be at least 256 bits (32 characters) for HS256.
 */

export const JWT_CONFIG = {
  // JWT secret - MUST be set via environment variable in production
  secret:
    process.env.JWT_SECRET || "your-super-secret-key-change-in-production",

  // Access token expiry in seconds (15 minutes)
  accessTokenExpiry: 15 * 60,

  // Refresh token expiry in seconds (7 days)
  refreshTokenExpiry: 7 * 24 * 60 * 60,

  // Stream token default expiry in seconds (1 hour)
  // Can be overridden per request for different streaming needs
  streamTokenExpiry: 60 * 60,

  // Cookie settings
  cookie: {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "strict" as const,
  },
};

/**
 * Generate a signed URL for video streaming
 * @param baseUrl - The base URL of the video manifest or segment
 * @param token - The stream token generated by authService.generateStreamToken
 * @returns The signed URL with token as query parameter
 */
export function generateSignedStreamUrl(
  baseUrl: string,
  token: string,
): string {
  const url = new URL(baseUrl);
  url.searchParams.set("token", token);
  return url.toString();
}

/**
 * Extract token from signed URL
 * @param url - The signed URL
 * @returns The token or null if not found
 */
export function extractTokenFromUrl(url: string): string | null {
  try {
    const urlObj = new URL(url);
    return urlObj.searchParams.get("token");
  } catch {
    return null;
  }
}
